name: Hermes Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Hermes product
        run: |
          echo "Checking Hermes..."

          curl -L -A "Mozilla/5.0" "https://www.hermes.com/fr/fr/product/bracelet-apple-watch-hermes-simple-tour-42mm-H0003241O89/" -o hermes.html

          echo "Page length:"
          wc -c hermes.html

          echo "Checking product page..."

          if grep -q "Ajouter au panier" hermes.html; then
            echo "🟢 STOCK FOUND"
          else
            echo "🔴 NO STOCK"
          fi
